# Workflow for using Cypress tests and generating reports to GitHub Pages.
name: Cypress Tests Workflow

# Runs on merges targeting the default branch.
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, don't cancel in-progress runs to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Run Cypress tests for Deck of Cards API
  cypress-run-deck:
    runs-on: ubuntu-latest
    steps:
      # Access GitHub repository to access its contents
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run deck tests
        uses: cypress-io/github-action@v6
        with:
          # Run tests and generate test results in cypress/reports/html/deck_of_cards_api
          command: npm run deck:run
      - name: Save HTML report folder
        uses: actions/upload-artifact@v4
        with:
          # Name artifact (file in cypress/reports/html/deck_of_cards_api) as deck_report
          name: deck_report
          path: cypress/reports/html/deck_of_cards_api
          if-no-files-found: error

  # Run Cypress tests for custom website
  cypress-run-custom:
    runs-on: ubuntu-latest
    steps:
      # Access GitHub repository to access its contents
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run custom website tests
        uses: cypress-io/github-action@v6
        with:
          # Start a local web server.
          start: npm start
          # Wait for the server to be ready before starting tests.
          wait-on: 'http://localhost:3000'
          # Run tests and generate test results in cypress/reports/html/custom_website
          command: npm run deck:run
      - name: Save HTML report folder
        uses: actions/upload-artifact@v4
        with:
          # Name artifact (file in cypress/reports/html/custom_website) as custom_report
          name: custom_report
          path: cypress/reports/html/custom_website
          if-no-files-found: error

  # Build the page made of the Deck of Cards API test report
  build-pages:
    needs: [cypress-run-deck, cypress-run-custom]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download deck API report artifact
        uses: actions/download-artifact@v4
        with:
          # Put Deck of Cards API test report in github_pages
          name: deck_report
          path: github_pages
      - name: Download custom website report artifact
        uses: actions/download-artifact@v4
        with:
          # Put custom website test report in github_pages
          name: custom_report
          path: github_pages
      - name: Setup for GitHub Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          # Use the HTML files to build the GitHub Pages website
          source: ./github_pages/
      - name: Upload HTML report artifact
        uses: actions/upload-pages-artifact@v3

  # Deploy page
  deploy-pages:
    needs: build-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
